version: '3'

services:
  redis-node1:
    image: artifact.efarda.ir/docker/redis:7
    command: ["redis-server", "--cluster-enabled", "yes", "--bind", "0.0.0.0", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node1:/data
    network_mode: "host"

  redis-node2:
    image: artifact.efarda.ir/docker/redis:7
    command: ["redis-server", "--cluster-enabled", "yes", "--bind", "0.0.0.0", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node2:/data
    network_mode: "host"

  redis-node3:
    image: artifact.efarda.ir/docker/redis:7
    command: ["redis-server", "--cluster-enabled", "yes", "--bind", "0.0.0.0", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node3:/data
    network_mode: "host"

  redis-node4:
    image: artifact.efarda.ir/docker/redis:7
    command: ["redis-server", "--cluster-enabled", "yes", "--bind", "0.0.0.0", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node4:/data
    network_mode: "host"

  redis-node5:
    image: artifact.efarda.ir/docker/redis:7
    command: ["redis-server", "--cluster-enabled", "yes", "--bind", "0.0.0.0", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node5:/data
    network_mode: "host"

  redis-node6:
    image: artifact.efarda.ir/docker/redis:7
    command: ["redis-server", "--cluster-enabled", "yes", "--bind", "0.0.0.0", "--cluster-config-file", "nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes"]
    volumes:
      - ./data/node6:/data
    network_mode: "host"

  init-redis-cluster:
    image: artifact.efarda.ir/docker/redis:7
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
    entrypoint: >
      sh -c "
        sleep 10 &&
        echo 'Creating Redis cluster' &&
        redis-cli --cluster create 172.16.238.2:6379 172.16.238.3:6379 172.16.238.4:6379 172.16.238.5:6379 172.16.238.6:6379 172.16.238.7:6379 --cluster-replicas 1 --cluster-yes
      "
    network_mode: "host"