version: "3"
services:
  freeipa:
    image: freeipa/freeipa-server:latest
    command:
      [
        "--realm=RESAA.IO",
        "--ds-password=123qwe!@#QWE",
        "--admin-password=123qwe!@#QWE",
        "-U"
      ]
    hostname: ipa.resaa.io
    container_name: freeipa
    restart: always
    #    networks:
    #      freeipa
    #network_mode: host
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 380:80
      - 3443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    volumes:
      - /opt/freeipa/data:/data:Z
      - /opt/freeipa/logs:/var/logs:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /var/cache
      - /tmp
#    networks:
#      freeipa:
#        enable_ipv6: true
